name: Build Windows Binaries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}
          git fetch origin
          git checkout ${{ github.ref }}

      - name: Install Node.js
        run: |
          Invoke-WebRequest -Uri https://nodejs.org/dist/v18.19.1/node-v18.19.1-x64.msi -OutFile node.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/i', 'node.msi', '/quiet', '/norestart'

      - name: Install Rust
        run: |
          Invoke-WebRequest -Uri https://win.rustup.rs/ -OutFile rustup-init.exe
          Start-Process -Wait -FilePath .\rustup-init.exe -ArgumentList "-y"
          $env:PATH += ";$env:USERPROFILE\.cargo\bin"

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload Tauri artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-build
          path: src-tauri\target\release\bundle
